#!/bin/bash

OPTS="-f html --strip-h-path -p"

NEEDNAME="yes"

while [ $# -gt 0 ] ; do

    if [ "$NEEDNAME" == "yes" ] && [ ${1:0:1} != '-' ] ; then
	OPTS="$OPTS -n"
	NEEDNAME="no"
    fi

    OPTS="$OPTS $1"
    shift

done

echo "kdoc $OPTS"
kdoc $OPTS
