#! /bin/sh
TGT="${1-.}"
if [ -d "$TGT"/.svn ]; then
    TS="$TGT"/.svn/entries
    T=$(mktemp /tmp/condup.XXXXXX) || exit
    touch -d '1 hour ago' $T
    if [ $TS -nt $T ]; then
	BYE=1
    fi
    rm $T
    if [ "$BYE" = 1 ]; then
	echo >&2 "New enough, skipped"
	exit
    fi
fi
svn up "$TGT"

