#! /bin/sh
# set environment for prefixed yast
# requiring an explicit PREFIX
if [ -z "$PREFIX" ]; then
    echo "PREFIX must be set" >&2
    exit 1
fi

# usage:
# prepend VARNAME VAL [SEPARATOR]
prepend() {
    export $1="${2}${!1+${3-:}${!1}}"
}

export PS1='[${PREFIX##*/}]:\w\$ '
export Y2DIR=$PREFIX/share/YaST2
MY_PERL_VENDORARCH=`perl -V:vendorarch | sed "s,.*=',,;s,'.*,," | sed "s,/usr,$PREFIX," `
prepend PKG_CONFIG_PATH "$PREFIX/share/pkgconfig:$PREFIX/lib/pkgconfig"
prepend PERL5LIB "$MY_PERL_VENDORARCH"
prepend PATH "$PREFIX/bin"
LIB=lib
if [ -d /usr/lib64 ]; then
    LIB=lib64
fi
prepend LD_LIBRARY_PATH "$PREFIX/$LIB"
"$@"
