#! /bin/sh
# set environment for prefixed yast
if [ $# = 0 ]; then
    echo "Usage: $0 <program> <arguments>" >&2
    exit 1
fi
: ${PREFIX=$HOME/pfx}
export PREFIX
PATH=$PREFIX/bin:$PATH
export Y2DIR=$PREFIX/share/YaST2
MY_PERL_VENDORARCH=`perl -V:vendorarch | sed "s,.*=',,;s,'.*,," | sed "s,/usr,$PREFIX," `
# FOO=BAR${FOO+:$FOO}
# if there was something, append it after a colon
export PKG_CONFIG_PATH=$PREFIX/share/pkgconfig:$PREFIX/lib/pkgconfig${PKG_CONFIG_PATH+:$PKG_CONFIG_PATH}
export PERL5LIB="$MY_PERL_VENDORARCH${PERL5LIB+:$PERL5LIB}"
"$@"
