#! /bin/sh
UI=qt
case $0 in
      *yp1) UI=ncurses;;
esac

while getopts v FLAG; do
    case $FLAG in
	v) VALGRIND=valgrind;;
	*) echo Ugh; exit 1;;
    esac
done
shift $((OPTIND-1))

CLIENT="$1"
shift
# Transform every argument into a ycp string, that is surround all
# args by ("...").  args may contain spaces.
a=("$@")
a=("${a[@]/#/(\"}")
a=("${a[@]/%/\")}")
set -- "${a[@]}"
pfx $VALGRIND ~mvidner/pfx/lib/YaST2/bin/y2base "$CLIENT" "$@" $UI
