#! /bin/sh
UI=qt
case $0 in
      *yp1) UI=ncurses;;
esac

while getopts vgs FLAG; do
    case $FLAG in
	v) : ${VALGRIND=valgrind} ;;
	g) : ${VALGRIND="gdb --args"} ;;
	s) : ${VALGRIND="strace -f -o strace.log"} ;;
	*) echo Ugh; exit 1;;
    esac
done
shift $((OPTIND-1))

CLIENT="$1"
shift
# Transform every argument into a ycp string, that is surround all
# args by ("...").  args may contain spaces.
a=("$@")
a=("${a[@]/#/(\"}")
a=("${a[@]/%/\")}")
set -- "${a[@]}"
: ${PREFIX=~mvidner/pfx}
pfx $VALGRIND $PREFIX/lib/YaST2/bin/y2base "$CLIENT" "$@" $UI
