#!/bin/bash
# $Id$
# usage: $0 [-t "Foo built-ins"] [-a] ../src/*.cc > Foo-builtins.html

if [ "$1" = "-t" ]; then
    TITLE=$2
    shift; shift
else
    TITLE="The YCP standard built-in functions"
fi

{
 echo $TITLE
 /usr/lib/YaST2/bin/builtindoc "$@"
} | /usr/lib/YaST2/bin/makehtml
