#!/bin/sh
#
# This script checks whether or not you have everything installed you need
# to compile a YaST2 module. Go to the module's top level directory
# (where the .spec.in file should be) and invoke this script.
# If RPM complains about something not installed, install it.
#
# Author:  Stefan Hundhammer <sh@suse.de>
# Updated: 2006-05-12
#

SPEC_FILES=*.spec.in
PKGS=`sed -ne '/BuildRequires/s/BuildRequires[ \t]*:[ \t]*//p' $SPEC_FILES | tr '\n' ' ' | sort -u`
rpm -q -- $PKGS
