#!/bin/sh

PKGS=`grep -h neededforbuild */*.spec.in | tr ' ' '\n' | sort -u | egrep -v '^(#)|(neededforbuild)|(gpp)|(libgpp)|(yast2-devel-packages)|(qt3-devel-packages)'$ | egrep -v -- '^-?yast2.*$'`
MISSING=`rpm -q -- $PKGS | grep "not installed" | sed -e 's/^package //' -e 's/ is not installed$//'`

if [ -z "$MISSING" ]; then
    echo "All required packages are installed"
else
    echo "MISSING PACKAGES" >&2
    echo "$MISSING"
fi
