#!/bin/sh
#
# This script checks whether or not you have everything installed you need
# to compile a YaST2 module. Go to the module's top level directory
# (where the .spec.in file should be) and invoke this script.
# If RPM complains about something not installed, install it.
#
# Author:  Stefan Hundhammer <sh@suse.de>
# Updated: 2004-05-12
#

rpm -q `sed -ne '/neededforbuild/s/# neededforbuild//p' *.spec.in` | \
egrep -v ' (gpp)|(libgpp) '
