#!/bin/bash -e

function usage () {
cat <<EOF
Usage:   giveheader AUTHOR MAINTAINER file1.cc file2.h ...
Example: giveheader "Mathias Kettner <kettner@suse.de>" "Harri Hirsch <harri@hirsch.to"
EOF
exit 5
}

AUTHOR="$1"
if [ -z "$AUTHOR" ] ; then
    usage
fi
shift 

MAINTAINER="$1"
if [ -z "$MAINTAINER" ] ; then
    usage
fi
shift


for file in $*
do
    TMPFILE=$(mktemp /tmp/giveheader.XXXXXX) || exit 1
    if [ ! -r "$file" ] ; then
	echo "$file: no such file" >&2
        continue;
    fi
    echo -n "$file..." >&2
    FILENAME=${file##*/}
cat <<EOF > $TMPFILE
/*---------------------------------------------------------------------\\
|                                                                      |
|                      __   __    ____ _____ ____                      |
|                      \ \ / /_ _/ ___|_   _|___ \                     |
|                       \ V / _\` \___ \ | |   __) |                    |
|                        | | (_| |___) || |  / __/                     |
|                        |_|\__,_|____/ |_| |_____|                    |
|                                                                      |
|                               core system                            |
|                                                        (C) SuSE GmbH |
\\----------------------------------------------------------------------/

   File:       $FILENAME

   Author:     $AUTHOR
   Maintainer: $MAINTAINER

/-*/
EOF
    if fgrep -q '/-*/' $file ; then
	sed '1,/\/-\*\//d' $file >> $TMPFILE
    else
	cat $file >> $TMPFILE
    fi

    cp $TMPFILE $file.new && mv $file.new $file && echo "OK" >&2
    rm -f $TMPFILE
done
