#!/bin/bash
# $Id$
# usage: $0 [-t "Foo built-ins"] [-a] ../src/*.cc > Foo-builtins.html

if [ "$1" = "-t" ]; then
    TITLE=$2
    shift; shift
else
    TITLE="The YCP standard built-in functions"
fi

SELF=`type -p $0`
SELFDIR=${SELF%/*}
{
 echo $TITLE
 $SELFDIR/builtindoc "$@"
} | $SELFDIR/makehtml
