#! /bin/sh
# for each FOO.out, parse FOO*.ycp
YCPDOC=../src/ycpdoc

echo
echo $0

FAIL=""
for OUT in *.out; do
    CASE=${OUT%.out}
    echo
    echo Running $CASE:
    $YCPDOC -f xml $CASE*.ycp
    mv ycpdoc.xml $CASE.out.tmp
    diff -u $OUT $CASE.out.tmp || FAIL=1
done

if [ $FAIL ]; then
    exit 1
fi
