#! /bin/sh 
# bless the test output as OK
# $1: test case, FOO or FOO.drv
ACT=test-html-act
# only one
for CASE in $ACT/*.drv; do
    CASE=${CASE#$ACT/}
    CASE=${CASE%.drv}
    for HTML in $ACT/*.html; do
	cp -av $HTML $CASE-${HTML#$ACT/}
    done
done

