#! /bin/sh
# for each FOO.drv, parse FOO*.ycp and compare the output
# Or run only $1.
YCPDOC=../src/ycpdoc

echo
echo $0

FAIL=""
for DRV in ${1-*.drv}; do
    CASE=${DRV%.drv}
    echo
    echo Running $CASE:
    # prepare the expected results
    EXP=test-html-exp
    rm -rf $EXP
    mkdir $EXP
    cp -a $DRV $EXP
    for HTML in $CASE*.html; do
	cp -a $HTML $EXP/${HTML#$CASE-}
    done
    # produce the actual test results
    ACT=test-html-act
    rm -rf $ACT
    mkdir $ACT
    cp -a $DRV $ACT
    $YCPDOC --format=html --outputdir=$ACT $CASE*.ycp
    if test $? != 0 || ! diff -ur $EXP $ACT; then
	FAIL=1
	break
    fi
done

if [ $FAIL ]; then
    exit 1
fi
