#!/bin/bash

# Creates a .pot file for a translator
#
# Usage makepot <ycp-file> <pot-file>
#
# sed-changes added by ml@suse.de, nov, 1999
# Adapted to new YaST2 layout by kkaempf@suse.de, May 2000

# creates messages.po

xgettext --language=YCP \
	 --width=0 \
	 --add-comments \
	 --keyword=_ \
	 $1

	rm -f $2
#	mv $module.po $module/$module.pot
	export module_sed=`basename $1`
	sed -e "s|Copyright (C) YEAR Free Software Foundation, Inc.|Copyright (C) SuSE GmbH, $(date +%Y).|g; \
s|SOME DESCRIPTIVE TITLE|LANGUAGE message file for YaST2 ($(echo $module_sed))|g"\
 < messages.po > $2
rm messages.po

exit 0

