#!/bin/sh
#
# kill-leftover-stuff - delete leftover files after devtools migration,
#			e.g. COPYING, COPYRIGHT.{english,french,german}
#
# Author: Stefan Hundhammer <sh@suse.de>
# (c) SuSE AG 2002
#

self=`basename $0`

if [ ! -e VERSION -o ! -e Makefile.cvs -o ! -e *.spec.in ]; then
    echo "${self}: FATAL: `pwd` is not a YaST2 project toplevel directory." >&2
    exit 1;
fi

if ! grep -q "y2automake" Makefile.cvs; then
    echo "${self}: FATAL: This project is not yet migrated to yast2-devtools." >&2
    exit 1;
fi


cvs -q rm -f COPYING COPYRIGHT.{english,french,german}


cvs -qn up
echo "`pwd` done - don't forget to check in your changes!"
