#!/bin/sh
# https://bugzilla.novell.com/show_bug.cgi?id=470981

VARIANTS=".cvsignore _cvsignore" 
if [ "$1" = -h -o "$1" = --help ]; then
    echo >&2 "Starts in CWD and converts [$VARIANTS] into svn:ignore in the subdirectories"
    exit 0
fi

if [ ! -d .svn ]; then
    echo >&2 "There is no .svn here, bye"
    exit 1
fi

for VARIANT in $VARIANTS YETTI; do
    if [ -f $VARIANT ]; then
	break
    fi
done
if [ $VARIANT = YETTI ]; then
    echo >&2 "None of [$VARIANTS] are present, bye"
    exit 1
fi

find . -name $VARIANT | \
    while read I; do
	if svn propset svn:ignore -F $I $(dirname $I); then
	    svn rm $I || rm $I
	fi
    done

echo >&2 "Serving suggestion: svn ci -m 'Converted $VARIANT to svn:ignore'"
